from typing import Any

class GlueContext:
    spark_session: Any

    def __init__(self, spark_context: Any) -> None: ...
    def getSink(self, **kwargs: Any) -> Any: ...
    def purge_s3_path(self, path: str, options: dict[str, Any]) -> Any: ...
